image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

before_script:
  - docker info

build:
  stage: build
  script:
    # Build the Docker image using your Dockerfile
    - docker build -t my-vite-app:latest .
    # Create a container from the built image
    - docker create --name my-vite-app-container my-vite-app:latest
    # Copy the built files from the container to the CI/CD workspace
    - docker cp my-vite-app-container:/app/dist ./dist
    # Clean up the container
    - docker rm my-vite-app-container
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
    # Move the built files to the public directory
    - mv dist/ public/
  artifacts:
    paths:
      - public
  only:
    - main  # or your default branch
