image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

build:
  stage: build
  script:
    # Build the Docker image using Dockerfile.production
    - docker build -f Dockerfile.production -t gummicube-demo-front:latest .
    # Create a container from the built image
    - docker create --name gummicube-demo-front-container gummicube-demo-front:latest
    # Copy the built files from the container to the CI/CD workspace
    - docker cp gummicube-demo-front-container:/app/dist ./dist
    # Clean up the container
    - docker rm gummicube-demo-front-container
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
    # Create public directory if it doesn't exist
    - mkdir -p public
    # Move contents of dist/ into public/
    - mv dist/* public/
  artifacts:
    paths:
      - public
  only:
    - main # or your default branch
