services:
  gummicube-demo-front:
    image: vite
    build:
      context: .
      dockerfile: Dockerfile.${NODE_ENV:-production}
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    ports:
      - 3000:3000
