services:
  gummicube-demo-front:
    image: gummicube-demo-front
    build:
      context: .
      dockerfile: Dockerfile.${NODE_ENV:-production}
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    ports:
      - 3001:3001
